### ISSUE TITLE
Allow toggling of features in swipe

### ISSUE THREAD

**Issue by shoe788** [Esri/arcgis-dijit-layer-swipe-js#10]
The swipe dijit just places the swipe layer on top of existing layers and doesn't clip the layer underneath. Any features underneath bleed through onto the swipe layer. This is fine in some circumstances but in others you want your swipe layer to be visible on the swiping side but another layer visible on the other side.

Is it possible to get an option to have non-swipe layers clipped so that their features are not visible on the swipe side?

**Comment by driskull** [comment]
Hey @shoe788 you can specify multiple layers to "swipe" which will clip them. It only clips the ones that the widget is supplied.

**Comment by driskull** [comment]
@shoe788 I think I understand. You want an option to hide the layers that aren't being swiped on the swipe side. I'll have to think about that.

It would be another option for clipLayers[] that would clip the layers on the swipe side. It's doable but would be a little bit of work.

**Comment by shoe788** [comment]
Yes exactly. The purpose would be to satisfy the condition where each side maintains their own layers instead of a "main" side and swipe side.

**Comment by traecooper** [comment]
I'd also like to see this functionality.  I'm working on an app that will allow our staff to compare two different versions of the FEMA 100 year floodplain.   Since the floodplain increases in some areas and decreases in others, overlaying the two doesn't work well.  And toggling the layers on and off isn't as clean as being able to swipe back and forth.

**Comment by driskull** [comment]
I think this is something we'll work into the 4.x version of this widget.
